# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

# Find icons at: https://www.nerdfonts.com/cheat-sheet

# Inserts a blank line between shell prompts
add_newline = true

format = """
$custom\
$line_break\
$character"""

[custom.path]
command = """
{{{file:scripts/starship.nu}}}

prompt "#000000" ({
  path:'{{{color:white}}}',
  package: '{{{color:brightPurple}}}',
  repo: '{{{color:brightPurple}}}',
  branch: '{{{color:brightBlack}}}'
})"""
shell = ["nu", "-c"]
when = true
format = "[$output]($style)"
style = "13"
