/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type Tag =
  | "autism"
  | "math"
  | "learn"
  | "statistics"
  | "simulation"
  | "programming"
  | "python"
  | "science"
  | "biology"
  | "experiments"
  | "tools"
  | "productivity"
  | "node"
  | "webdev"
  | "javascript"
  | "documentation"
  | "writing"
  | "devops"
  | "discuss"
  | "computer-science"
  | "encoding"
  | "serialization"
  | "communication"
  | "binary"
  | "beginners"
  | "data"
  | "linux"
  | "windows"
  | "docker"
  | "html"
  | "css"
  | "email"
  | "marketing"
  | "typescript"
  | "tutorial"
  | "video"
  | "expressjs"
  | "json"
  | "phd"
  | "vscode"
  | "motivation"
  | "mental-health"
  | "adhd"
  | "life"
  | "philosophy"
  | "privilege"
  | "definition"
  | "evolution"
  | "media"
  | "recipe"
  | "coffee"
  | "critique"
  | "notion"
  | "ergonomics"
  | "health"
  | "permissions"
  | "security"
  | "authentication"
  | "npm"
  | "testing"
  | "tdd"
  | "mochajs"
  | "gamedev"
  | "google"
  | "business"
  | "apple"
  | "cors"
  | "cookies"
  | "http"
  | "jsdoc";
export type Duration = string;

export interface BlogPost {
  /**
   * The unique identifier for the blog post
   */
  slug: string;
  title: string;
  description: string;
  canonical?: string;
  tags: Tag[];
  legacySlug?: string;
  editedAt?: string;
  publishedAt: string;
  recipe?: {
    name: string;
    description: string;
    image: string;
    recipeInstructions?: HowToStep[];
    recipeIngredient?: string[];
    prepTime?: Duration;
    cookTime?: Duration;
    totalTime?: Duration;
    [k: string]: unknown;
  };
  [k: string]: unknown;
}
export interface HowToStep {
  "@type": "HowToStep";
  text: string;
  [k: string]: unknown;
}
