on:
  push:
    tags:
      - "@adam-coster/site@*"
    branches:
      - "preview"
      - "preview/*"

defaults:
  run:
    shell: bash

jobs:
  publish:
    name: Publish to Cloudflare
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - run: corepack enable
      - run: npm run setup:pnpm
      - run: pnpm ci:site
      - run: pnpm ci:publish
        env:
          CLOUDFLARE_API_TOKEN: ${{secrets.CLOUDFLARE_API_TOKEN}}
        working-directory: "./projects/site"
